### ISSUE TITLE
Link to logo in `guidelines.md` leads to 404 error

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscommunityafrica/docs#14]
The path for the O.S.C.A Logo provided in `guidelines.md` is not relative.
The logo link should be gotten from GitHub user raw content

**Comment by BolajiAyodeji** [comment]
![image](https://user-images.githubusercontent.com/30334776/48689291-113e0b00-ebca-11e8-90b4-f91d68389480.png)

**Comment by samswag** [comment]
Would you want to send a fix?

**Comment by BolajiAyodeji** [comment]
YES

**Comment by samswag** [comment]
Okay great, waiting for you PR

**Comment by BolajiAyodeji** [comment]
Sent!

**Comment by Yomdroid** [comment]
This issue has been resolved right?

**Comment by BolajiAyodeji** [comment]
Yes @Yomdroid 
You can check all other sections for bugs too.
