### ISSUE TITLE
Retaining woman in open source: Organising Open Source Day monthly

### ISSUE THREAD

**Issue by tapaswenipathak** [oscommunityafrica/docs#20]
Hi folks: Finding an active open source contributor or maintainer woman is hard. Internships give a break in open source, if observed there is no retention of women in open source and research[1] suggests. Implementing open source day per month letting woman work with mentor and contribute in an open source project they would like would be practical implementation than just publishing research and articles. Lemme know if you would interested in supporting. I will share further information.

[1] https://en.wikipedia.org/wiki/Diversity_in_open-source_software

**Comment by samswag** [comment]
Hi, @tapaswenipathak I am interested to hear more of what you are proposing. I believe in complete diversity too.

**Comment by tapaswenipathak** [comment]
On Sun, 25 Aug 2019, 05:45 Samson Goddy, <notifications@github.com> wrote:

> Hi, @tapaswenipathak <https://github.com/tapaswenipathak> I am interested
> to hear more of what you are proposing. I believe in complete diversity too.
>

Hey, I will email the proposal out.
